CREATE TABLE IF NOT EXISTS GIFT (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	description varchar(255),
	giftstatus varchar(255),
	occassion varchar(255)
);

create sequence demo_sequence start with 1 increment by 1;
